title: PHPing.me
description: Overview of PHP essetials and it userland 
canonical: http://phping.me 
owner:
  - twitter: seva_dolgopolov

links:
  - title: Functions
    url: /functions
  - title: Provisioning
    url: /provisioning


collections:
  functions:
    output: true
  provisioning:
    output: true

highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


